from . import cartes
from . import promotion
from . import fidelite
from . import notifications
from . import rapports
from . import carte_condition
from . import cartes_reduction_info
from . import cartes_client
from . import cartes_attribution
from . import loyalty_card
from . import loyalty_mail
from . import loyalty_rule
from . import loyalty_program
from . import product_product
from . import product_template
from . import res_partner
from . import loyalty_reward
from . import product_pricelist
from . import product_pricelist_item
from . import partner
from . import wizard_renouvellement
from . import PosSession
from . import sale_order
from . import RewardSelectionWizard
from . import website
from . import sale_order_line
from . import dashboard_vente
from . import dashboard_product_sales
from . import Dashboard_client
from . import cartes_dashboard
from . import promotion_rule
from . import data_ml
from . import ProductAssociation
from . import ProductSuggestionWizard